
import colorama 
from colorama import Fore
import os 
import datetime
import time 

os.system(' clear ')
time.sleep(0.1)
print(Fore.CYAN+"`mMMMMMMMMMMMNmmdhy-")
time.sleep(0.1)
print(Fore.CYAN+" dMMMMMMMMMMMMMMMMMMs`")
time.sleep(0.1)
print(Fore.CYAN+" +MMsohNMMMMMMMMMMMMMm/")
time.sleep(0.1)
print(Fore.CYAN+" .My   .+dMMMMMMMMMMMMMh.")
time.sleep(0.1)
print(Fore.CYAN+"  +       :NMMMMMMMMMMMMNo")
time.sleep(0.1)
print(Fore.CYAN+"           `yMMMMMMMMMMMMMm:")
time.sleep(0.1)
print(Fore.CYAN+"             /NMMMMMMMMMMMMMy`")
time.sleep(0.1)
print(Fore.CYAN+"              .hMMMMMMMMMMMMMN+")
time.sleep(0.1)
print(Fore.CYAN+"                  ``-NMMMMMMMMMd-")
time.sleep(0.1)
print(Fore.CYAN+"                     /MMMMMMMMMMMs`")
time.sleep(0.1)
print(Fore.CYAN+"                      mMMMMMMMsyNMN/")
time.sleep(0.1)
print(Fore.CYAN+"                      +MMMMMMMo  :sNh.")
time.sleep(0.1)
print(Fore.CYAN+"                      `NMMMMMMm     -o/")
time.sleep(0.1)
print(Fore.CYAN+"                       oMMMMMMM.")
time.sleep(0.1)
print(Fore.CYAN+"                       `NMMMMMM+")
time.sleep(0.1)
print(Fore.CYAN+"                        +MMd/NMh")
time.sleep(0.1)
print(Fore.CYAN+"                         mMm -mN`")
time.sleep(0.1)
print(Fore.CYAN+"                         /MM  `h:")
time.sleep(0.1)
print(Fore.CYAN+"                          dM`   .")
time.sleep(0.1)
print(Fore.CYAN+"                          :M-")
time.sleep(0.1)
print(Fore.CYAN+"                           d:")
time.sleep(0.1)
print(Fore.CYAN+"                           -+")
time.sleep(0.1)
print(Fore.CYAN+"                            -")
time.sleep(0.1)
print(Fore.MAGENTA+" ===========installs will start soon========================")
time.sleep(5)
os.system(' pip install colorama ')
time.sleep(1)
os.system(' pip install psutil ')
time.sleep(1)
os.system(' git clone https://github.com/dylanaraps/neofetch.git ')
time.sleep(1)
os.system(' git clone https://github.com/ArkAngeL43/GN-Scraper.git ')
time.sleep(1)
os.system(' git clone https://github.com/ArkAngeL43/PH-tracer.git ')
time.sleep(1)
os.system(' git clone https://github.com/ArkAngeL43/bash-automation-brute.git ')
time.sleep(1)
os.system(' git clone https://github.com/ArkAngeL43/toxic.git ')
time.sleep(1)
os.system(' clear ')
os.system(' clear ')
time.sleep(2)
print(Fore.RED+" ==================")
os.system(' date ')
print(Fore.RED+" ==================")
time.sleep(2)
os.system(' clear ')
print(" |----------------------------|")
print(" |thank you for installing    |")
print(" |and using Ark_Angels scripts|")
print(" |----------------------------|")
time.sleep(3)
os.system(' clear ')