os.system(' clear ')
time.sleep(0.1)
print(Fore.CYAN+"`mMMMMMMMMMMMNmmdhy-")
time.sleep(0.1)
print(Fore.CYAN+" dMMMMMMMMMMMMMMMMMMs`")
time.sleep(0.1)
print(Fore.CYAN+" +MMsohNMMMMMMMMMMMMMm/")
time.sleep(0.1)
print(Fore.CYAN+" .My   .+dMMMMMMMMMMMMMh.")
time.sleep(0.1)
print(Fore.CYAN+"  +       :NMMMMMMMMMMMMNo")
time.sleep(0.1)
print(Fore.CYAN+"           `yMMMMMMMMMMMMMm:")
time.sleep(0.1)
print(Fore.CYAN+"             /NMMMMMMMMMMMMMy`")
time.sleep(0.1)
print(Fore.CYAN+"              .hMMMMMMMMMMMMMN+")
time.sleep(0.1)
print(Fore.CYAN+"                  ``-NMMMMMMMMMd-")
time.sleep(0.1)
print(Fore.CYAN+"                     /MMMMMMMMMMMs`")
time.sleep(0.1)
print(Fore.CYAN+"                      mMMMMMMMsyNMN/")
time.sleep(0.1)
print(Fore.CYAN+"                      +MMMMMMMo  :sNh.")
time.sleep(0.1)
print(Fore.CYAN+"                      `NMMMMMMm     -o/")
time.sleep(0.1)
print(Fore.CYAN+"                       oMMMMMMM.")
time.sleep(0.1)
print(Fore.CYAN+"                       `NMMMMMM+")
time.sleep(0.1)
print(Fore.CYAN+"                        +MMd/NMh")
time.sleep(0.1)
print(Fore.CYAN+"                         mMm -mN`")
time.sleep(0.1)
print(Fore.CYAN+"                         /MM  `h:")
time.sleep(0.1)
print(Fore.CYAN+"                          dM`   .")
time.sleep(0.1)
print(Fore.CYAN+"                          :M-")
time.sleep(0.1)
print(Fore.CYAN+"                           d:")
time.sleep(0.1)
print(Fore.CYAN+"                           -+")
time.sleep(0.1)
print(Fore.CYAN+"                            -")
time.sleep(0.1)
print(Fore.MAGENTA+" =================setup will start soon========================")
time.sleep(5)
os.system(' pip install python_weather ')
time.sleep(1)
os.system(' pip install colorama ')
time.sleep(1)
os.system(' pip install phonenumbers ')
time.sleep(1)
os.system(' pip install tabulate ')
time.sleep(1)
os.system(' pip install scapy ')
time.sleep(1)
os.system(' pip install gTTS ')
time.sleep(1)
os.system(' pip install requests_html ')
time.sleep(1)
os.system(' pip install dill ')
time.sleep(1)
os.system(' pip install gtts ')
time.sleep(1)
os.system(' sudo apt-get install nodejs ')
time.sleep(1)
os.system(' sudo apt-get install npm ')
time.sleep(1)
os.system(' sudo npm install -g corona-cli ')
time.sleep(1)
os.system(' pip install turtle ')
time.sleep(1)
os.system(' pip install requests ')
time.sleep(1)
os.system(' pip install requests_html ')
time.sleep(1)
os.system(' git clone https://github.com/dylanaraps/neofetch.git ')
time.sleep(1)
os.system(' git clone https://github.com/ArkAngeL43/cpu-info.git ')
time.sleep(1)
os.system(' git clone https://github.com/ArkAngeL43/weather-scraping.git ')
time.sleep(1)
os.system(' git clone https://github.com/ArkAngeL43/GN-Scraper.git ')
time.sleep(1)
os.system(' git clone https://github.com/ArkAngeL43/PH-tracer.git ')
time.sleep(1)
os.system(' git clone https://github.com/ArkAngeL43/toxic.git ')
time.sleep(1)
os.system(' clear ')
os.system(' clear ')
print("=============================== ")
os.system(' date ')
print("===============================")
time.sleep(2.5)
os.system(' clear ')
print("+=====================================+")
print("+thank you for installing requirments +")
print("+=====================================+")
time.sleep(3)
os.system(' clear ')